Implement an option to keep pinned tabs in all open windows
Faerbit/persistentpin-webextension pull request #16
Opened 2022-01-25 07:35 UTC by Sharsie

Implementation of persistent pin across all open windows, resolves #9

I don't speak german, so a translation would be handy if this would ever be merged.

To be honest, I'm not sure why the "initialized", previously "opened_tabs" flag was there, I wasn't able to replicate the behaviour, where the background.js would ever execute more than once. But I kept it there to be safe.

2022-03-12 11:17 UTC, Faerbit requested changes

2022-03-12 11:17 UTC, Faerbit commented on _locales/de/messages.json
> +        "message": "Pin the websites in all opened windows",
```suggestion
        "message": "Hefte die Tabs in allen Fenstern an",
```

2022-03-12 11:17 UTC, Faerbit commented on src/background.js
> +                pinned_websites.forEach(function(website) {
Somehow this is undefined when first loading the addon (`about:debugging` -> "Load temporary Add-On..." -> "Inspect"). Which leads me to believing the current iteration would break loading the pinned tabs on initial startup. Have you tested this?

Im am unsure as to why this is happening, however with the master branch it is not according to my testing.

2022-03-12 11:17 UTC, Faerbit commented
Thanks for your contribution! Sorry it took me so long to get around to this. See above for my comments.

2022-03-12 11:24 UTC, Faerbit commented on src/background.js
> +                pinned_websites.forEach(function(website) {
Sorry, I just didn't test right. This happens on first installation, due to preferences not being setup right/not handled graciously. This happens also with the master branch and is effectively no problem. Your changes didn't break anything as far as I can tell

2022-03-12 11:24 UTC, merged

2022-03-13 09:22 UTC, Sharsie commented on src/background.js
> +                pinned_websites.forEach(function(website) {
Yea, I think I came accross that when testing in an anonymous/dev window, I thought I would get to fixing some of the things in another PR, but never got around to it. There are a couple of things I would do differently, but I wanted to maintain the code style and the way it was written as to not introduce any confusion for anyone else in the future, so many of the things regarding the config/setup are just c&p&rename :)

2022-03-13 09:22 UTC, Sharsie commented
Thanks! No worries, I'm not really using it that way anyway, but thought it could be helpful to some.